using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

/// <summary>
/// https://leetcode.com/problems/find-the-difference/#/description
/// 
/// 
/// Given two strings s and t which consist of only lowercase letters.
///
///String t is generated by random shuffling string s and then add one more letter at a random position.
///
///Find the letter that was added in t.
///
///Example:
///
///Input:
///s = "abcd"
///t = "abcde"
///
///Output:
///e
///
///Explanation:
///'e' is the letter that was added.
/// 
/// </summary>
namespace LeetCode
{
    class FindDiffString
    {
        /// <summary>
        /// String is an array of characters and each character is a ASCII code. Add all ASCII codes of characters of string one and string two . result is substraction of resultant sums
        /// </summary>
        /// <param name="s"></param>
        /// <param name="t"></param>
        /// <returns></returns>
        public char FindTheDifference(string s, string t)
        {
            int sumFirstString = 0;
            int sumSecondString = 0;

            foreach (char c in s)
                sumFirstString += c;

            foreach (char c in t)
                sumSecondString += c;

            return (char)(sumSecondString-sumFirstString);
        }
    }
}
